# Generated by Django 2.2.7 on 2020-05-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0002_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
